# Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/creditcard.csv')

In [3]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
49605,44132,-1.211298,-0.450385,1.440502,0.354908,-0.408886,1.636777,-0.951234,1.185703,-1.020024,...,0.086607,0.526001,0.191522,-1.026321,-0.529712,-0.057442,0.125643,0.000680,79.00,0.0
49606,44132,1.176642,0.154754,0.246080,0.800814,-0.590838,-1.487705,0.336949,-0.316725,-0.047056,...,-0.008572,-0.105115,-0.017629,0.937907,0.463495,0.332980,-0.062039,0.016149,40.00,0.0
49607,44133,-1.103844,0.186527,1.568397,1.307678,0.316942,0.290415,1.147621,-0.222930,0.000022,...,-0.160645,0.468407,0.389831,0.213000,-0.015877,-0.278962,0.322504,-0.270168,108.00,0.0
49608,44134,-0.262018,0.851831,1.459865,1.057694,-0.725526,0.274325,1.750817,-1.097029,0.439934,...,-0.272138,0.032569,-0.141121,0.476174,-0.587678,0.288669,-0.914934,-0.676786,172.82,0.0
49609,44135,-4.719790,-4.249875,1.850000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49610 entries, 0 to 49609
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    49610 non-null  int64
 1   V1      49610 non-null  float64
 2   V2      49610 non-null  float64
 3   V3      49610 non-null  float64
 4   V4      49609 non-null  float64
 5   V5      49609 non-null  float64
 6   V6      49609 non-null  float64
 7   V7      49609 non-null  float64
 8   V8      49609 non-null  float64
 9   V9      49609 non-null  float64
 10  V10     49609 non-null  float64
 11  V11     49609 non-null  float64
 12  V12     49609 non-null  float64
 13  V13     49609 non-null  float64
 14  V14     49609 non-null  float64
 15  V15     49609 non-null  float64
 16  V16     49609 non-null  float64
 17  V17     49609 non-null  float64
 18  V18     49609 non-null  float64
 19  V19     49609 non-null  float64
 20  V20     49609 non-null  float64
 21  V21     49609 non-null  float64
 22  V22     49609 non-null  float64
 23  V23     49609 non-null  float64
 24  V24     49609 non-null  float64
 25  V25     49609 non-null  float64
 26  V26     49609 non-null  float64
 27  V27     49609 non-null  float64
 28  V28     49609 non-null  float64
 29  Amount  49609 non-null  float64
 30  Class   49609 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 11.7 MB

In [6]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [15]:
credit_card_data = credit_card_data.drop([49609])

In [16]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [17]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
49604,44132,-1.623757,-1.486672,3.191250,-0.613841,-1.316739,0.585336,-0.005224,0.389628,2.427135,...,0.305795,0.903998,0.229926,0.383144,0.588491,-0.383920,-0.108623,-0.118653,246.76,0.0
49605,44132,-1.211298,-0.450385,1.440502,0.354908,-0.408886,1.636777,-0.951234,1.185703,-1.020024,...,0.086607,0.526001,0.191522,-1.026321,-0.529712,-0.057442,0.125643,0.000680,79.00,0.0
49606,44132,1.176642,0.154754,0.246080,0.800814,-0.590838,-1.487705,0.336949,-0.316725,-0.047056,...,-0.008572,-0.105115,-0.017629,0.937907,0.463495,0.332980,-0.062039,0.016149,40.00,0.0
49607,44133,-1.103844,0.186527,1.568397,1.307678,0.316942,0.290415,1.147621,-0.222930,0.000022,...,-0.160645,0.468407,0.389831,0.213000,-0.015877,-0.278962,0.322504,-0.270168,108.00,0.0
49608,44134,-0.262018,0.851831,1.459865,1.057694,-0.725526,0.274325,1.750817,-1.097029,0.439934,...,-0.272138,0.032569,-0.141121,0.476174,-0.587678,0.288669,-0.914934,-0.676786,172.82,0.0

In [18]:
# distribution of legit transactions and fraudulent transactions
credit_card_data['Class'].value_counts()

0.0    49461
1.0      148
Name: Class, dtype: int64

*notice that this data is extremely unbalanced

0 -> normal transaction

1 -> fraudulent transaction

In [19]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [20]:
print(legit.shape)
print(fraud.shape)

(49461, 31)
(148, 31)

In [21]:
# statistical measures of the data
legit.Amount.describe()

count    49461.000000
mean        93.099593
std        253.325102
min          0.000000
25%          7.680000
50%         25.000000
75%         85.000000
max      12910.930000
Name: Amount, dtype: float64

In [22]:
fraud.Amount.describe()

count     148.000000
mean      100.170676
std       233.347471
min         0.000000
25%         1.000000
50%         9.560000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [23]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,28809.010473,-0.220239,-0.003947,0.726173,0.167967,-0.240785,0.111250,-0.096470,0.042413,0.134593,...,0.046113,-0.031134,-0.106800,-0.039391,0.008275,0.135623,0.020410,0.003001,0.004455,93.099593
1.0,26877.182432,-7.675017,5.448919,-10.398242,5.939649,-5.681176,-2.280722,-8.068966,3.739332,-3.587074,...,0.470319,0.886835,-0.225326,-0.284732,-0.084733,0.246743,0.155479,0.603171,0.030658,100.170676

# Under-Sampling (dealing with unbalanced data)

Build a sample dataset containing similar distribution of normal transactions and fraudulent transactions

Number of fraudulent transactions --> 148

In [24]:
legit_sample = legit.sample(n=148)

Concatenating two dataframes

In [25]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [26]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
2839,2417,-0.339403,1.159029,1.300822,0.058592,0.053263,-0.972624,0.740550,-0.093539,-0.448055,...,-0.259686,-0.660597,-0.018147,0.343663,-0.148886,0.070672,0.247820,0.099010,3.87,0.0
30691,36039,1.263203,-0.079517,0.443452,0.260903,-0.284663,0.246596,-0.524798,0.204555,0.328186,...,-0.121328,-0.416726,-0.053802,-0.841492,0.257880,0.270997,-0.017302,0.002745,5.99,0.0
37470,38968,1.300916,-0.112141,-0.505086,-1.100102,-0.241779,-1.413955,0.402782,-0.316888,1.115116,...,-0.361239,-1.083972,-0.016638,-0.180655,0.612340,-0.984002,0.015224,0.017728,35.71,0.0
8350,11163,-0.483971,0.482274,1.605304,-0.603256,-0.098256,-0.442161,0.092873,0.041258,1.163763,...,-0.190078,-0.436887,0.070796,-0.041116,-0.350352,0.825914,-0.200012,-0.023543,5.96,0.0
18073,29165,-0.876387,-0.259946,2.614146,-2.029389,-0.125564,1.941531,-0.543664,0.711308,-0.687850,...,0.424516,1.564688,-0.298299,-1.000479,0.141304,-0.027751,0.206367,-0.121301,17.00,0.0

In [27]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
46909,42985,-4.075975,0.963031,-5.076070,4.955963,-0.161437,-2.832663,-7.619765,1.618895,-2.992092,...,1.030738,0.165328,-1.017502,-0.477983,-0.304987,-0.106089,1.899714,0.511462,1.00,1.0
46918,42988,-4.423508,1.648048,-6.934388,4.894601,-5.078131,0.010849,-3.409096,1.409291,-3.260672,...,0.698359,0.487478,1.228698,-0.535217,0.388278,-0.009466,2.300164,0.081231,648.00,1.0
46998,43028,-1.109646,0.811069,-1.138135,0.935265,-2.330248,-0.116106,-1.621986,0.458028,-0.912189,...,0.641594,0.841755,0.176728,0.081004,-0.258899,0.707654,0.418649,0.080756,204.27,1.0
47802,43369,-3.365319,2.426503,-3.752227,0.276017,-2.305870,-1.961578,-3.029283,-1.674462,0.183961,...,2.070008,-0.512626,-0.248502,0.126550,0.104166,-1.055997,-1.200165,-1.012066,88.00,1.0
48094,43494,-1.278138,0.716242,-1.143279,0.217805,-1.293890,-1.168952,-2.564182,0.204532,-1.611155,...,0.490183,0.470427,-0.126261,-0.126644,-0.661908,-0.349793,0.454851,0.137843,24.90,1.0

In [28]:
new_dataset['Class'].value_counts()

0.0    148
1.0    148
Name: Class, dtype: int64

In [29]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,29242.560811,-0.110823,-0.018255,0.840189,0.044934,-0.284734,0.157500,-0.142954,0.059422,0.105585,...,0.033251,-0.050936,-0.037183,-0.069890,-0.072073,0.152134,0.021599,0.003108,0.032922,81.913311
1.0,26877.182432,-7.675017,5.448919,-10.398242,5.939649,-5.681176,-2.280722,-8.068966,3.739332,-3.587074,...,0.470319,0.886835,-0.225326,-0.284732,-0.084733,0.246743,0.155479,0.603171,0.030658,100.170676

# Splitting the data into features & targets

In [30]:
X = new_dataset.drop(columns='Class', axis=1)
y = new_dataset['Class']

In [31]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
2839    2417 -0.339403  1.159029  1.300822  0.058592  0.053263 -0.972624
30691  36039  1.263203 -0.079517  0.443452  0.260903 -0.284663  0.246596
37470  38968  1.300916 -0.112141 -0.505086 -1.100102 -0.241779 -1.413955
8350   11163 -0.483971  0.482274  1.605304 -0.603256 -0.098256 -0.442161
18073  29165 -0.876387 -0.259946  2.614146 -2.029389 -0.125564  1.941531
...      ...       ...       ...       ...       ...       ...       ...
46909  42985 -4.075975  0.963031 -5.076070  4.955963 -0.161437 -2.832663
46918  42988 -4.423508  1.648048 -6.934388  4.894601 -5.078131  0.010849
46998  43028 -1.109646  0.811069 -1.138135  0.935265 -2.330248 -0.116106
47802  43369 -3.365319  2.426503 -3.752227  0.276017 -2.305870 -1.961578
48094  43494 -1.278138  0.716242 -1.143279  0.217805 -1.293890 -1.168952

             V7        V8        V9  ...       V20       V21       V22  \
2839   0.740550 -0.093539 -0.448055  ...  0.136317 -0.259686 -0.660597
30691 -0.524798  0.204555  0.328186  ... -0.091948 -0.121328 -0.416726
37470  0.402782 -0.316888  1.115116  ... -0.121742 -0.361239 -1.083972
8350   0.092873  0.041258  1.163763  ... -0.151498 -0.190078 -0.436887
18073 -0.543664  0.711308 -0.687850  ...  0.141291  0.424516  1.564688
...         ...       ...       ...  ...       ...       ...       ...
46909 -7.619765  1.618895 -2.992092  ...  0.058861  1.030738  0.165328
46918 -3.409096  1.409291 -3.260672  ... -0.562264  0.698359  0.487478
46998 -1.621986  0.458028 -0.912189  ...  0.168891  0.641594  0.841755
47802 -3.029283 -1.674462  0.183961  ... -0.036837  2.070008 -0.512626
48094 -2.564182  0.204532 -1.611155  ...  0.817203  0.490183  0.470427

            V23       V24       V25       V26       V27       V28  Amount
2839  -0.018147  0.343663 -0.148886  0.070672  0.247820  0.099010    3.87
30691 -0.053802 -0.841492  0.257880  0.270997 -0.017302  0.002745    5.99
37470 -0.016638 -0.180655  0.612340 -0.984002  0.015224  0.017728   35.71
8350   0.070796 -0.041116 -0.350352  0.825914 -0.200012 -0.023543    5.96
18073 -0.298299 -1.000479  0.141304 -0.027751  0.206367 -0.121301   17.00
...         ...       ...       ...       ...       ...       ...     ...
46909 -1.017502 -0.477983 -0.304987 -0.106089  1.899714  0.511462    1.00
46918  1.228698 -0.535217  0.388278 -0.009466  2.300164  0.081231  648.00
46998  0.176728  0.081004 -0.258899  0.707654  0.418649  0.080756  204.27
47802 -0.248502  0.126550  0.104166 -1.055997 -1.200165 -1.012066   88.00
48094 -0.126261 -0.126644 -0.661908 -0.349793  0.454851  0.137843   24.90

[296 rows x 30 columns]

In [32]:
print(y)

2839     0.0
30691    0.0
37470    0.0
8350     0.0
18073    0.0
        ...
46909    1.0
46918    1.0
46998    1.0
47802    1.0
48094    1.0
Name: Class, Length: 296, dtype: float64

# Split the data into Training data & Testing data

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=2)

In [34]:
print(X.shape, X_train.shape, X_test.shape)

(296, 30) (236, 30) (60, 30)

# Model Training

Logistic Regression (for binary classification models)

In [35]:
model = LogisticRegression()

In [36]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Model Evaluation

Accuracy Score

In [37]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, y_train)

In [38]:
print('Accuracy on Training data: ', training_data_accuracy)

Accuracy on Training data:  0.9703389830508474

In [39]:
# accuracy on testing data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, y_test)

In [40]:
print('Accuracy on Testing data: ', test_data_accuracy)

Accuracy on Testing data:  0.9833333333333333